name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code from master
        run: |
          cd /home/github_runner/Siprent-client
          git pull origin master
