name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: | 
          npm ci
          npm run build

  deploy:
    name: Deploy To Production
    runs-on: self-hosted
    needs: test

    steps:
      - name: Setup Automation to Server
        run: |
          #!/bin/bash

          set -e  # Stop jika ada error
          
          cd /var/www/html/Sipren-client
          
          echo "Git Pull"
          git config --global --add safe.directory /var/www/html/Sipren-client
          git fetch origin
          git reset --hard origin/master
          git clean -fd
          
          echo "Copy .env"
          cp /home/github_runner/actions-runner/.env_sipren_fe .env
          
          echo "Install dependencies"
          npm install
          
          echo "Build React App"
          npm run build
          
          echo "Deploy complete"
