name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: | 
          npm ci
          npm run build

  deploy:
    name: Deploy To Production
    runs-on: self-hosted
    needs: test

    steps:
      - name: Setup Automation to Server
        run: |
          sh /home/github_runner/actions-runner/test_deploy.sh
