name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build Frontend
        run: |
          cd frontend-sipren
          npm ci
          npm run build

  deploy:
    name: Deploy Dockerized App
    runs-on: self-hosted
    needs: test

    steps:
      - name: Pull latest code
        run: |
          cd /var/www/html/SIPREN
          git config --global --add safe.directory /var/www/html/SIPREN
          git fetch origin
          git reset --hard origin/master
          git clean -fd

      - name: Copy .env files
        run: |
          cp /home/github_runner/actions-runner/.env_sipren_fe frontend-sipren/.env
          cp /home/github_runner/actions-runner/.env_sipren_be backend-sipren/.env
          cp /home/github_runner/actions-runner/.env_sipren_db .env

      - name: Stop and Remove Old Containers
        run: docker-compose down -v

      - name: Build and Start New Containers
        run: docker-compose up -d --build

      - name: Show Running Containers
        run: docker ps
