name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: /home/github_runner/actions-runner/deploy.sh